[package]
name = "hyperlocal"
version = "0.4.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Hyper bindings for unix domain sockets"
homepage = "https://github.com/softprops/hyperlocal"
repository = "https://github.com/softprops/hyperlocal"
keywords = ["hyper", "unix", "sockets", "http"]
license = "MIT"

[dependencies]
hyper = "0.11"
tokio-uds = "0.1"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-service = "0.1"
